apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 383944855594.dkr.ecr.ap-southeast-2.amazonaws.com/myapp-repo
  newName: 383944855594.dkr.ecr.ap-southeast-2.amazonaws.com/myapp-repo
  newTag: 995a024c
resources:
- ../../base
patchesStrategicMerge:
- myapp-deployment-patch.yaml
- myapp-service-patch.yaml
